### ISSUE TITLE
SD and Audio works

### ISSUE THREAD

**Issue by ghost** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#10]
So, i am running Ubuntu Mate 17.04, and thanks to your script, sound and Sd Card works but only with a "workaround" (i dont no how to spell in english, sry) 

I have to put in the SD Card every start, so it can be recognized.
And the sound works if you take chtcx2072x as Default than the Atom Processor x5.

Many thanks to you grippentech ;) Awesome work Linux rocks on my Asus E200HA :D

**Comment by Grippy98** [comment]
Yeah that seems to be the case right now. Hopefully it can be resolved by the time the changes hit mainline kernel builds! Glad you're enjoying it! :)

**Comment by ghost** [comment]
Yes hopefully ;) would be awesome if it would work "out of the box" ;)
