### ISSUE TITLE
Can't get to work on Ubuntu 17.04

### ISSUE THREAD

**Issue by davidbullmore** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#14]
First of all, thank you for making this. This has been a problem for almost a year for everyone running Ubuntu on an E200HA, and you fixed it.

I am currently running 17.04. I couldn't get it to work :\ wouldn't detect the device, nothing.

I tried installing 16.10, and my keyboard wouldn't work. Everytime I hit a key it would call the shutdown function.

I'm pretty new to Linux, I am possibly doing something wrong. I followed the guide, and installed directly after 17.04, but yeah, couldn't get it to work :\

**Comment by gravemalte** [comment]
Please open the terminal and type `uname -r` after that let me know what the output is.

**Comment by davidbullmore** [comment]
It's currently 4.11.3, as I was trying a few new Kernels to see if anything had fixed in updated.

It was 4.10 when I used this package.

**Comment by gravemalte** [comment]
Are you sure that was 4.10.xx-custom or 4.10.xx ?

**Comment by davidbullmore** [comment]
I will try again now and report back :)

**Comment by davidbullmore** [comment]
I reinstalled everything but my Kernel is now still 4.11.3. 

Should I get 4.11.rc5? Or should I use the Kernel provided? If so, which ones need to be installed? Thanks again

**Comment by gravemalte** [comment]
It's all okay. So you need to setup that the "new" kernel will boot. Simply follow my instruction. First run this command `sudo cp /etc/default/grub /etc/default/grub.bak`  this will backup your boot config. If anything goes wrong this is your restore  file. After that run `sudo nano /etc/default/grub`. Now your have a black window with some text, please be careful. Now look for the line `GRUB_DEFAULT`  you will change this line to this `GRUB_DEFAULT="Advanced options for Ubuntu>Ubuntu, with Linux 4.10.0-custom"`. Last step run `sudo update-grub`. Thats all just reboot and you're done. Remember if your system doesn't boot correctly, just restore the config.

**Comment by davidbullmore** [comment]
Yeah this worked perfectly. I removed the 4.11.3 kernel, but even then it reverted back to 4.10.0-generic. Did this and it works great :) Thank you for getting back to me. Issue resolved.

**Comment by Grippy98** [comment]
Thanks for covering for me while I'm on vacation Daylien :D, glad you managed to get it working David.
