### ISSUE TITLE
Run attempt returns newline error

### ISSUE THREAD

**Issue by Happytin** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#18]
Hello,

When I try to run either the e200ha_with_sound.sh script or the justSound.sh scripts I get:

./e200ha_with_sound.sh:  ./e200ha_with_sound.sh: Syntax error: newline unexpected

Each time I run the script I will get an error returned stating that the newline is in a different place (ie line 1, line 7 etc). I know you planned to do a commit to correct this yesterday but this hasn't happened so I thought I'd just check in with what's happening.

I only just got my e200ha and have been through the whole drama of the OS I picked not playing with the wifi so switching OS, then my keyboard not playing, and I feel like you are now my final god of salvation XD

Cheers
Kat

**Comment by Grippy98** [comment]
Hey Kat, 

Have you tried downloading the repository files themselves and executing the script that way instead of (what I assume you are doing) which is to copy the text from Github? Some users have that issue and it's related to your text editor not seeing each line of the script file. 

Let me know if that helps fix the issue.

**Comment by Happytin** [comment]
Hi,

Sadly I am downloading the file itself and executing it that way. I feel like I must be doing something really stupid. Thanks for your time and patience.

The exact error I get is:
./e200ha_with_sound.sh: 8: ./e200ha_with_sound.sh: Syntax error: newline unexpected

I don't know if it's at all relevant but I'm running Linux Mint 18.2.

**Comment by Grippy98** [comment]
Hmm just make sure that every line looks properly indented. It just seems like there are terminating characters that aren't being recognized. Have you checked it with a text editor that every line appears on it's own and there aren't any weird "\n" characters or such at the end of lines?

**Comment by Happytin** [comment]
Weirdly, I tried copying and pasting the code instead and it ran like a dream! Who even knows what happened there?! Thanks for your time and effort though. I have sound and everything now. You're wonderful, thank you so much.
