### ISSUE TITLE
Unstable on Ubuntu 17.04, but new kernel 4.12.8 published

### ISSUE THREAD

**Issue by filip7k** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#19]
Hi,

On my Asus E200HA sound works fine. Thank you. Problem is that its now easy possible to make system unstable. Often my Unity crash and I got back to login page, while all programs are closed.

New stable kernel has came: 4.12.8. I downloaded it and installed, but sound went away. How to try sound on kernel 4.12.8 ?

**Comment by Grippy98** [comment]
Hey Filip,

The sound modifications are based around a custom version of the kernel and
I haven't had time to see what the exact sound changes are (to merge them
in a cohesive matter with the mainline kernel), I will try to get an
updated version out this following week. If you have issues under unity you
might try a different desktop environment like LXDE, for some reason Unity
and some others become unstable under the kernel with the sound patches.

All the best,
Andrei

**Comment by filip7k** [comment]
Andrei,

I did actualization of bios to BIOS 303. Im embarrassed I haven't done it before. 
Now I have connection of new bios + Ubuntu 17.04 + apt-get update & upgrade + yours kernel and everything is very very stable in Unity. Possible to play YouTube + Netflix + mp4 in the same time.

It doesn't change the fact that that I'm looking forward for new, stable version of kernel. Thanks.

BTW: Sandisk Ultra 16GB SD doesn't want to cooperate with this Asus.

**Comment by Grippy98** [comment]
Glad you got it to work! I'm back to working on this so look forward to a smaller version based on kernel 4.13 rc6 sometime by the end of this week depending on how busy my classes end up being.
