### ISSUE TITLE
Bluetooth/HSP not working

### ISSUE THREAD

**Issue by yevmel** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#2]
there is one more thing you could add to your list of broken things. Audio over Bluetooth does not work when using HSP profile.

**Comment by Grippy98** [comment]
I'll look into it tonight. What headphones are you trying this with? If bluetooth works at all I believe any audio profiles should* work.

**Comment by yevmel** [comment]
hi,

i have tried multiple headphones (Motorola Moto Surround and Plantronics Backbeat Sense) with the same result: A2DP works out of the box with current Bluez + Pulseaudio on my Arch Linux installation. HSP does not work. Looking through Pulseaudio Bugzilla i found other people with similar issue.

https://bugs.freedesktop.org/show_bug.cgi?id=99226 (my open issue)
https://bugs.freedesktop.org/show_bug.cgi?id=97064
https://bugs.freedesktop.org/show_bug.cgi?id=73325 (older posts describe a different, already solved issue, but the last few posts sound like the same issue)

txh for your feedback.

**Comment by yevmel** [comment]
> If bluetooth works at all I believe any audio profiles should* work.

exactly what i thought. sounds like a software issue, so i asked for help in Bugzilla from Pulseaudio project. There i found others with different hardware, but similar problem. According to experienced sounding users it looks like a firmware or (device-)configuration problem.

**Comment by Grippy98** [comment]
Hmm ok interesting. I didn't get a chance to look at it last night but I'll try in a couple hours.

**Comment by Grippy98** [comment]
I thought I'd wait for Kernel 4.10 to drop before I work on this anymore. Stable is supposed to be released this Sunday so I'll test then.

**Comment by yevmel** [comment]
i am running a release candidate of 4.10 and still have the same issues (sleep/wakeup does not work, no sound, Bluetooth/HSP not working). If people from https://bugs.freedesktop.org are right and this is a firmware/configuration issue, then a newer kernel won't fix the Bluetooth/HSP issue.
