### ISSUE TITLE
Using Ubuntu Budgie, Sound is not working, but device detected

### ISSUE THREAD

**Issue by ghost** [Grippentech/Asus-E200HA-Linux-Post-Install-Script#8]
Hey,
thanks for your work but on my Asus E200HA with Ubuntu Budgie everything works fine and the soundcard is detected but it's not working :c As output device there's after installing the new kernel: Analog output - Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Configuration Registers

PS: Before using your patch I've updated to kernel 4.11rc8

Can you help me pls? :)

**Comment by Grippy98** [comment]
What does the command 'uname -r' return? It should have a kernel name that returns in - custom at the end. Otherwise you need to set my version of the kernel manually and delete your newer one

**Comment by jiocol** [comment]
This is my configuration of pulseaudio working on ubuntu budgie. [http://i.imgur.com/F1lOnjE.png]( http://i.imgur.com/F1lOnjE.png)
To prevent youtube videos to stop playing after a while I set pulseaudio to autorun on startup.

**Comment by Grippy98** [comment]
Thanks for confirming it works. @sammox2016 Your issue is most likely that you're not loading my version of the kernel since you had a newer version installed.
